import modules.archive
import modules.dellog
import modules.login
import modules.restart
import modules.embederror
import modules.hitler
import modules.roles
import modules.licorne
import modules.ekiller
